# -*- coding: utf-8 -*-
"""Projeto 2.ipynb

Automatically generated by Colab.

Original file is located at
 https://github.com/AndreFGard
  (Redacted! talk to me if you wish to have access to the notebook)

**Alunos:** Andrefgard, ********

Este dataset é baseado em transações de imóveis em 2023. O objetivo principal foi comparar informações sobre os imóveis da Madalena e das Graças, dois bairros vizinhos, localizados na região central da cidade do Recife. É importante destacar que só foram considerados como de interesse para esta análise os imóveis avaliados em valores menores que um milhão de reais.
"""


#download https://www.kaggle.com/datasets/adamrbarr/recife-real-estate-transactions-2015-to-2023?resource=download
#rename the table relative to the year of interest to "itbi.csv"
data = read.csv("itbi.csv",sep=";")

install.packages("ggplot2")
library('ggplot2')

data =subset(data, 1 == 1, c(bairro, area_construida,tipo_imovel,ano_construcao,valor_avaliacao)) #ano_construcao é usado para obter as idades

"""
# **Descrição das variáveis**
- **bairro**: Variável qualitativa nominal; indica o bairro onde está o imóvel.
- **idade**: Variável quantitativa contínua; indica a idade do imóvel e se baseia no ano de construção dele.
- **área construída**: Variável quantitativa contínua; representa a área construída do imóvel
- **tipo do imóvel**: Variável qualitativa nominal; classifica o tipo do imóvel entre categorias como apartamento, casa, sala e loja.
- **valor avaliação**: Variável quantitativa contínua; é o valor de avaliação do imóvel."""

#Os bairros Madalena e Graças foram escolhidos para a análise e possuem uma quantidade parecida de transações registradas na amostra
bairrofreq = as.data.frame(table(data$bairro)) #quantidade de transacoes por bairro
bairrofreq = subset(bairrofreq, Var1 %in% c("MADALENA", "GRACAS")) #filtrado para madalena e graças
bairrofreq[order(bairrofreq$Freq), ]

getvalorbairro = function(bairron) {
  valoresbairro = na.omit(subset(data, bairro == bairron))

  #nestas linhas pode-se alternar entre um valor fixo e um valor limite relativo
  #valoresbairro = subset(valoresbairro, valor_avaliacao <= quantile(valoresbairro$valor_avaliacao, 0.90))
  valoresbairro = subset(valoresbairro, valor_avaliacao <= 10^6)

  print(paste0("VALORES MAIORES QUE O SEGUINTE NO BAIRRO ", bairron, " SERAO IGNORADOS"))
  #print(quantile(valoresbairro$valor_avaliacao, 0.90))
  print(10^6)

  #converter os valores do formato char(145,3) para float(145.3)
  valoresbairro$area_construida = as.numeric(gsub(",", ".",valoresbairro$area_construida))

  valoresbairro$idade = 2024 - valoresbairro$ano_construcao
  valoresbairro$precom2 = valoresbairro$valor_avaliacao/ valoresbairro$area_construida
  return(valoresbairro)
}

valores_gracas = getvalorbairro("GRACAS")
valores_madalena = getvalorbairro("MADALENA")

getinfo = function (data){
  cat("média de valores:", mean(data))
  cat("\nmediana dos valores: ", median(data))
  cat("\ndesvio padrão dos valores: ", sd(data))
  hdata = hist(data, plot=FALSE)
  #intervalo mais frequente:
  cat("\nIntervalo mais frequente dos valores:", hdata$mids[which.max(hdata$counts)], hdata$mids[which.max(hdata$counts) + 1])
  cat("\nquartis: ", quantile(data, probs = c(0.25, 0.5, 0.75)))
}

cat("\n###################################", "INFORMACOES SOBRE OS PREÇOS DAS GRAÇAS\n")
getinfo(valores_gracas$valor_avaliacao)
cat("\n\n###################################", "INFORMACOES SOBRE AS IDADES DE IMÓVEIS DAS GRAÇAS\n")
getinfo(valores_gracas$idade)
cat("\n\n###################################", "INFORMACOES SOBRE A ÁREA DOS IMÓVEIS DAS GRAÇAS\n")
getinfo(valores_gracas$area_construida)


cat("\n\n\n#####################################################################################\n")
cat("\n\n###################################", "INFORMACOES SOBRE OS PREÇOS DA MADALENA\n")
getinfo(valores_madalena$valor_avaliacao)
cat("\n\n###################################", "INFORMACOES SOBRE AS IDADES DE IMÓVEIS DA MADALENA\n")
getinfo(valores_madalena$idade)
cat("\n\n###################################", "INFORMACOES SOBRE A ÁREA DOS IMÓVEIS DA MADALENA\n")
getinfo(valores_madalena$area_construida)

#relacao entre area e idade
ggplot(valores_gracas, aes(x=idade, y=area_construida, color=valor_avaliacao)) + geom_point() + scale_color_gradient(low = "red", high = "green") + geom_smooth(method="loess", color="purple") + labs(title="Relação entre área e idade do imóvel nas GRAÇAS") + theme_minimal()
ggplot(valores_madalena, aes(x=idade, y=area_construida, color=valor_avaliacao)) + geom_point() + scale_color_gradient(low = "red", high = "green") + geom_smooth(method="loess", color="purple") + labs(title="Relação entre área e idade do imóvel na MADALENA") + theme_minimal()

"""Os gráficos de dispersão, que correlacionam a área dos imóveis em cada bairro com as suas respectivas idades, revelam que a relação entre idade e área construída do imóvel não é muito forte, em ambos os bairros."""

#histograma de idades (mudar pra grafico de pizza/setor)
ggplot(valores_gracas, aes(x = idade, fill = after_stat(count))) +
  geom_histogram(binwidth = 10) +
  scale_fill_gradient(low = "red", high = "green") +
  labs(title = "Distribuição da idade dos imoveis nas GRAÇAS",  y = "Frequencia") +
  theme_minimal()

ggplot(valores_madalena, aes(x = idade, fill = after_stat(count))) +
  geom_histogram(binwidth = 10) +
  scale_fill_gradient(low = "red", high = "green") +
  labs(title = "Distribuição da idade dos imoveis na MADALENA", y = "Frequencia") +
  theme_minimal()

"""Os histogramas que mostram a frequência de imóveis com cada idade indicam visualmente que o bairro das Graças possui imóveis, em média, mais velhos que os da Madalena, mas que ambos possuem muitos imóveis com menos de 25 anos."""

color_palette <- c(
  "Apartamento" = "#1f77b4",
  "Casa" = "#ff7f0e",
  "Centro Comercial/Serviços" = "#2ca02c",
  "Loja" = "#d62728",
  "Sala" = "#9467bd"
)

ggplot(as.data.frame(table(valores_gracas$tipo_imovel)), aes(x = "", y = Freq, fill = Var1)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = "Tipos de imóveis nas Graças", x = NULL, y = NULL) +
  theme(legend.position = "right") +
  scale_fill_manual(values = color_palette)


ggplot(as.data.frame(table(valores_madalena$tipo_imovel)), aes(x = "", y = Freq, fill = Var1)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = "Tipos de imóveis na Madalena", x = NULL, y = NULL) +
  theme(legend.position = "right") +
    scale_fill_manual(values = color_palette)

"""Percebe-se que, na Madalena, a relação entre casas e apartamentos parece ser bem maior do que nas Graças. Além disso, nas Graças, a relação entre lojas + salas e apartamentos parece maior do que na Madalena. Assim, os dados utilizados podem indicar que há uma maior disponibilidade de comércios nas Graças."""

t.test((valores_gracas$valor_avaliacao),valores_madalena$valor_avaliacao )

"""# Teste 1
Como os dados da amostra mostraram médias muito próximas dos valores dos imóveis, o teste de hipótese foi usado pra verificar se elas eram diferentes, usando **Ho** = as médias de valor dos imóveis são iguais e **Ha** = as médias são diferentes. Claramente, o teste de hipótese nos leva a ***não rejeitar a Hipótese Nula***.
"""

t.test(valores_gracas$area_construida, valores_madalena$area_construida, alternative = "greater")

"""# Teste 2
As medidas sobre as áreas de cada imóvel dos bairros pareciam indicar que as áreas construídas dos imóveis nas Graças eram maiores que as dos imóveis na Madalena e o teste de hipótese feito para avaliar isso (Ho = as áreas nas Graças são menores ou iguais que as na Madalena, Ha = as áreas nas Graças são maiores) indicou que não devemos rejeitar a Ho, para um intervalo de confiança de 5%.
"""
